name: shelf
version: 0.1.0
description: >-
  Twirp helper library used by generated code. It also exports some common Twirp Types.
author: Sri Krishan Paritala <srikrishna.paritala@gmail.com>
homepage: https://github.com/srikrsna/twirp_dart

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  http: ^0.12.0
